name: CardPlus Empower
favicon: null
layout_spectrum: 0.65818
typography_spectrum: 0.49011
title: Title Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#42b649'
    - '#0064b0'
    - '#676767'
    - '#94d598'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
